name: opencage_geocoder
description: Dart client for the OpenCage forward/reverse geocoding API
version: 0.0.5
homepage: https://github.com/aloisdeniel/dart-opencage-geocoder
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  json_annotation: "^0.2.2"

dev_dependencies:
  build_runner: "^0.6.1"
  json_serializable: "^0.3.0"
  test: "^0.12.0"
