name: opencage_geocoder
description: Dart client for the OpenCage forward/reverse geocoding API
version: 1.0.1
homepage: https://github.com/aloisdeniel/dart-opencage-geocoder
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.7.2 
  json_serializable: ^3.2.5
  test: ^1.9.4
