name: opencage_geocoder
description: Dart client for the OpenCage forward/reverse geocoding API
version: 2.0.0-dev.2
homepage: https://github.com/aloisdeniel/dart-opencage-geocoder

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^2.0.1
  build_runner: ^2.3.3 
  json_serializable: ^6.6.1
  test: ^1.24.2
