name: opencage_geocoder
description: Dart client for the OpenCage forward/reverse geocoding API
version: 0.1.0
homepage: https://github.com/aloisdeniel/dart-opencage-geocoder
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: "^3.0.0"

dev_dependencies:
  build_runner: "^1.7.2"
  json_serializable: "^3.2.3"
  test: "^1.9.4"
